[package]
name = "light-mp-serde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0" }
rmp = "0.8.11"
thiserror = "1.0.31"